### ISSUE TITLE
Adding an attribution line for the basemap in use automatically

### ISSUE THREAD

**Issue by mukil** [AtelierCartographie/Khartis#6]
I thought a bit about the 2nd questions described in issue #5.

> 2. I choose to make the basemaps available based on open data geometries published by the Bundesamt für Kartographie und Geodäsie. Officially, each map using these geometries should therefore include an attribution like described in the paragraph on License & Usage rights.

I think for our users it might be the most comfortable solution if we manage to include the attribution line/metadata directly into the respective basemap configuration section.

So, my proposal would be to add an **attribution** key to the part in the _/config/environment.js_  where we introduce new basemap, like e.g.

```
    {
        id: "german districts 2016",
        sources: [
          {
            source: "DE-2016/topojson/vg2500-BKG-NUTS3-combined.json",
          }
        ],
        dictionary: {
          source: "DE-BKG-NUTS3-2016.json",
          identifier: "RS"
        },
        attribution: "(C) GeoBasis-DE / BKG 2016",
        examples: []
    },
```
As I understand it Khartis users should' not need to worry (too much) about their usage rights of the geodata they select as a basemap and thus it is the responsability (of us as developers) to just select and integrate open data (or data where every potential user is granted a usage right suitable for e.g. map publication). With that line confgured i think it may be a good decision to include this line into any map export/design automatically e.g. in a way that users can move and place the map attribution but not necessarily hide it.

What do you think about this?

Cheers!

**Comment by boogheta** [comment]
Agreed on my part! I would even add an extra "licensing" field that would tell under which open conditions the map actually lies in (CC-BY, CC-BY-SA, Public Domain, ...?)
Then the question is where does this appear in the exports. We have a zone for the displayed data licensing and attribution, not for the maps, maybe just assemble them close to one another?
And it should definitely appear at least as meta in the export as well indeed!

What do you think @apezel @TomBor ?

**Comment by TomBor** [comment]
I think it's a good idea. As you say @mukil users don't need to worry about this, because if a basemap is in Khartis, it must be in open data. I made two pages in the wiki to cite [basemaps](https://github.com/AtelierCartographie/Khartis/wiki/Les-fonds-de-carte-disponibles) and [examples](https://github.com/AtelierCartographie/Khartis/wiki/Les-sources-des-exemples-%C3%A0-disposition) sources (*french*). It was a first step and your proposition is more integrated, legal and pedagogic.

A formulation like "Basemap based on [attribution value], [licensing value]" would be good to indicate source and transformation (*based on*). Most of the time we modify basemap by changing borders, simplify geometry, fix geometry, and dictionary can be aggregate from different sources. So it's not purely the original source.

About the position of this attribution, I would prefer to add it with the "Made with Khartis" zone. Because with a data source input and a credit input it's already enough complicated. But I'm open to other arguments.

**Comment by TomBor** [comment]
Thanks to @apezel we made good progress on attribution. So now, we have an attribution line in the config. For example:
```{
        id: "france dept",
        attribution: "basemap from OpenStreetMap contributors (ODbl license)",
        sources: [```

This attribution is visible at the bottom-right of the map and join to the "source" field.

**Comment by mukil** [comment]
Yay! Thanks a lot, this is great news, this means we could merge #6. I will give it a run immediately!

**Comment by mukil** [comment]
So, just to give you a "thumbs up" from my side :) 
Legally, thanks to our changes, the integration of the german basemaps in Khartis is now compliant with the "GeoNutzV" terms of the BKG open geodata (Source: [PDF](http://www.geodatenzentrum.de/docpdf/geonutzv.pdf), in German).

Please let me know if you need any assistance or help from my side to merge my contributions.
Thank you for your support!
